import { UserRole } from "@/types";

export const SYSTEM_PERMISSIONS = [
  "user_management",
  "user_view",
  "role_management",
  "property_management",
  "property_view",
  "property_create",
  "property_edit",
  "property_delete",
  "tenant_management",
  "tenant_view",
  "tenant_create",
  "tenant_edit",
  "lease_management",
  "lease_view",
  "lease_create",
  "lease_edit",
  "maintenance_management",
  "maintenance_view",
  "maintenance_create",
  "maintenance_assign",
  "maintenance_requests",
  "work_orders",
  "maintenance_history",
  "financial_management",
  "financial_reports",
  "payment_processing",
  "payment_portal",
  "payment_history",
  "system_settings",
  "audit_logs",
  "backup_restore",
  "bulk_operations",
  "company_settings",
  "data_export",
  "reports_all",
  "reports_property",
  "reports_own",
  "advanced_analytics",
  "application_processing",
  "screening_management",
  "document_access",
  "document_management",
  "profile_management",
] as const;

export type SystemPermission = (typeof SYSTEM_PERMISSIONS)[number];

export const SYSTEM_ROLE_PERMISSIONS: Record<
  UserRole,
  readonly SystemPermission[]
> = {
  [UserRole.ADMIN]: [
    "user_management",
    "user_view",
    "role_management",
    "property_management",
    "property_view",
    "property_create",
    "property_edit",
    "property_delete",
    "tenant_management",
    "tenant_view",
    "tenant_create",
    "tenant_edit",
    "lease_management",
    "lease_view",
    "lease_create",
    "lease_edit",
    "maintenance_management",
    "maintenance_view",
    "maintenance_create",
    "maintenance_assign",
    "maintenance_requests",
    "work_orders",
    "maintenance_history",
    "financial_management",
    "financial_reports",
    "payment_processing",
    "payment_portal",
    "payment_history",
    "system_settings",
    "audit_logs",
    "backup_restore",
    "bulk_operations",
    "company_settings",
    "data_export",
    "reports_all",
    "reports_property",
    "reports_own",
    "advanced_analytics",
    "application_processing",
    "screening_management",
    "document_access",
    "document_management",
    "profile_management",
  ],
  [UserRole.MANAGER]: [
  "property_management",
  "property_view",
  "property_create",
  "property_edit",

  "tenant_management",
  "tenant_view",
  "tenant_create",
  "tenant_edit",

  "lease_management",
  "lease_view",
  "lease_create",
  "lease_edit",

  "maintenance_management",
  "maintenance_view",
  "maintenance_create",
  "maintenance_assign",
  "work_orders",
  "maintenance_history",

  "financial_management",
  "financial_reports",
  "payment_processing",

  "document_management",
  "document_access",

  "application_processing",
  "screening_management",

  "profile_management",
],
  [UserRole.TENANT]: [
    "profile_management",
    "maintenance_requests",
    "payment_portal",
    "document_access",
    "lease_view",
    "payment_history",
    "maintenance_history",
    "reports_own",
  ],
};

export const ADMIN_ONLY_PERMISSIONS: readonly SystemPermission[] = [
  "user_management",
  "role_management",
  "system_settings",
  "audit_logs",
  "backup_restore",
  "data_export",
  "advanced_analytics",
];

export const MANAGER_LEVEL_PERMISSIONS: readonly SystemPermission[] = [
  "property_management",
  "property_view",
  "property_create",
  "property_edit",
  "property_delete",
  "tenant_management",
  "tenant_view",
  "tenant_create",
  "tenant_edit",
  "lease_management",
  "lease_view",
  "lease_create",
  "lease_edit",
  "maintenance_management",
  "maintenance_view",
  "maintenance_create",
  "maintenance_assign",
  "financial_management",
  "financial_reports",
  "payment_processing",
  "company_settings",
  "bulk_operations",
  "application_processing",
  "screening_management",
  "document_management",
  "reports_all",
  "reports_property",
];
